### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mcicekci** [dotnetcore/DotnetSpider#87] opened 2018-11-26 09:28 UTC
Hello there,
Dotnetspider good. Net crawler.
But I need documents.
I want to use it, but I don't know how to install and configure it.

**Comment by zlzforever** [comment] 2018-11-27 02:01
@wolverine81 hi, there is a sample project and a lot of example in docs folder. you can have a try to read them. I don't have enough time to write document until 1 month later. sry

**Comment by yang-xiaodong** [comment] 2019-08-16 13:41
Duplicate of #77

**Closed as completed by yang-xiaodong** 2019-08-16 13:41 UTC
Labels: help wanted
